name: Java CI

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
      with:
        java-version: 1.8
        - run: mvn verify -B -DskipTests
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
      with:
        java-version: 1.8
        - run: mvn test
  build:
    runs-on: ubuntu-latest
    needs: [ test,lint ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
      with:
        java-version: 1.8
        - run: mvn clean package

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
      with:
        java-version: 1.8
        - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/*.jar"
        token: ${{ secrets.GITHUB_TOKEN }}
        commitish: ${{ github.event.pull_request.base.sha || github.sha }}
        name: release-${{ steps.date.outputs.date }}
        prerelease: true

        - id: date
          run: echo "::set-output name=date::$(date +'%Y-%m-%d')"